---
- hosts: vm1
  
  tasks:
  - name: ping pong vm1
    ping:

  - name: use shell and query id
    shell: "ls /etc/yum.repos.d"
  - name: Get_url
    get_url:
       url: http://192.168.43.82:8090/local.repo
       dest: /etc/yum.repos.d/local.repo
       mode: "644"
  - name: Get_url
    get_url:
       url: http://192.168.43.82:8090/RPM-GPG-KEY-EPEL-8
       dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
       mode: "644"
  - name: Installation HTTPD
    yum:
      name: httpd
      state: latest
  - name: Stop service httpd, if started
    service:
      name: httpd
      state: started
      enabled: yes
  - name: Firewalld
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      immediate: yes



